# Railway 项目配置
# 此文件提供额外的部署选项

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./startup.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300

# 资源限制（可选，用于控制成本）
[resource]
# 免费计划的默认值
memoryGB = 0.5
cpuCount = 1

# 网络配置
[networking]
publicPort = 3333

# 环境变量
[env]
NODE_ENV = "production"
PORT = "3333"
DOCKER_SETUP = "true"
HOSTNAME = "0.0.0.0"

